### ISSUE TITLE
Support dropping fields during conversion

### ISSUE THREAD

**Issue by gabro** [kailuowang/henkan#14]
Given

``` scala
case class A(foo: String, bar: String)
case class B(foo: String)
```

I'd like to "shrink" an instance of `A` to `B`, but I get an error

``` scala
val a = A("hey", "ho")
val b = a.to[B]() // One of more fields of <shapeless repr of A> is not present in B
```

Is this already possible somehow?

If not, I would propose something like

``` scala
val a = A("hey", "ho")
val b = a.to[B].drop('bar)
```

**Comment by kailuowang** [comment]
hmm, you should be able to convert to case class with less fields without problem. 
I just tested your use case, `a.to[B]()` worked for me. Is this the code you used to repeat the error? If not can you post one? (and the actual compilation error message would be helpful as well)

**Comment by gabro** [comment]
Hey @kailuowang thanks for the answer. Actually as soon as I tried to reproduce it, I couldn't, so it was probably due to something else.

Anyway, the actual compilation message was the one in the comment

```
One of more fields of <shapeless repr of A> is not present in B
```

I can't reproduce it anymore, but in case I will I'll reopen this issue.
