### ISSUE TITLE
Error when the last field is a nested class 

### ISSUE THREAD

**Issue by zhenghub** [kailuowang/henkan#15]
I meet an error when transform a typesafe config to a case class below.

> case class Weapon(t: String, attack: Int, defense: Int)
> case class Weapon2(t: String, attack: Int)
> case class Person(name: String, weapon: Weapon, life: Long)
> case class WWeapon(weapon: Weapon)
> case class Person2(name: String, life: Long, weapon: Weapon)
> case class WWeapon2(weapon: Weapon2)

Class Weapon has two fields: attack and defense. Both are Int. It may cause some problems:

> val conf: Config
> extract [ Option, Weapon ](conf) // OK
> extract [ Option, Weapon2 ](conf) // OK
> extract [ Option, Person ](conf) // OK
> extract [ Option, WWeapon ](conf) // ERROR
> extract [ Option, Person2 ](conf) // ERROR
> extract [ Option, WWeapon2 ](conf) // ERROR
> implicitly[Extractor[Option,Config,Weapon]] // OK
> implicitly[Extractor[Option,Config,Weapon2]] // OK
> implicitly[Extractor[Option,Config,Person]] // OK
> implicitly[Extractor[Option,Config,WWeapon]] // ERROR
> implicitly[Extractor[Option,Config,Person2]] // ERROR
> implicitly[Extractor[Option,Config,WWeapon2]] // ERROR

scala 2.11, java 7, henken 0.1.0

**Comment by kailuowang** [comment]
Probably a bug. I would recommend you to use ficus for now. Since there is an ongoing attempt to fix SI2712 which affects henkan greatly, I am going to hold on making any change to it.

**Comment by kailuowang** [comment]
I noticed as well that henkan might got confused when the last field is a nested field. A work around could be having an implicit Extractor  of the nested class first.

**Comment by zhenghub** [comment]
I use the work around as below and it works

> **implicit val ev1 =** implicitly[Extractor[Option,Config,Weapon]] // OK. why announce the implicit value again works?
> **implicit val ev2 =** implicitly[Extractor[Option,Config,Weapon2]] // OK
> implicitly[Extractor[Option,Config,Person]] // OK
> implicitly[Extractor[Option,Config,WWeapon]] // OK
> implicitly[Extractor[Option,Config,Person2]] // OK
> implicitly[Extractor[Option,Config,WWeapon2]] // OK

I want to use henkan to handle not only typesafe configs but also serialization and unserialization to json and byte array, so Ficus cannot solve my problem. Since shapeless is still confusing to me and you consider not change henkan recently, could you give me some hints so I can fix this in my fork?

**Comment by kailuowang** [comment]
@zhenghub I don't have a clue how to fix this bug yet. but this scala fix https://github.com/scala/scala/pull/5102 will greatly simplify Henkan code, which will probably make it a lot easier to fix this problem. 
Have you looked at scala pickling yet? https://github.com/scala/pickling Henkan is still pretty immature, scala pickling is probably a more robust library for json/byte serialization.

**Comment by zhenghub** [comment]
@kailuowang I've tried https://github.com/netvl/picopickle . It fixed the bug. But it is quite complicated to adapt picopickle to typesafe config, since many classes of typesafe config are not public which conflicts with picopickle's type transformation implementation. Meaning I need to write another series of classes as intermediate conversion. I would try pickling next.

**Comment by kailuowang** [comment]
closing this because the experimental extract module has been removed.
