### ISSUE TITLE
Handle conversions where the key is the same but the type differs

### ISSUE THREAD

**Issue by joprice** [kailuowang/henkan#16]
If the two classes have a field with the same name but different types, the conversion fails to compile, even if the value is provided and is of the correct type.

**Comment by kailuowang** [comment]
That's actually a common use case. I don't quite understand why it's happening. I thought two fields with the same name but different value types would be just two different fields. But clearly somewhere the value type gets erased or something. I'll look into this after scala days.

**Comment by kailuowang** [comment]
fixed by #20
