### ISSUE TITLE
Publish 0.4.2 for 2.11

### ISSUE THREAD

**Issue by joprice** [kailuowang/henkan#38]
Even though cross versions is configured, there is no scala.211 artifact for v0.4.2.

**Comment by kailuowang** [comment]
ah, the `releaseCrossBuild := true` must be set at the root module, although that one is not published. 
Just released 0.4.4 for both 2.11 and 2.12

**Comment by kailuowang** [comment]
closing for now, the artifacts should be on their way to maven central.

**Comment by joprice** [comment]
Still not there. How long does it take?

**Comment by kailuowang** [comment]
Hmm, if you add
`resolves += Resolver.sonatypeRepo("releases")` to you build, would you get it?

**Comment by kailuowang** [comment]
see it on maven central now.

**Comment by joprice** [comment]
It works now. Thanks!
