### ISSUE TITLE
Overriding optional fields in a case class

### ISSUE THREAD

**Issue by pigate** [kailuowang/henkan#46]
I'm having trouble converting between case classes that contain some optional fields and overriding the optional fields.

See this example: 
```
case class A(a: Int, b: Option[Int])
case class B(a: Int, b: Option[Int], c: String)
object B {
  def from(a: A): B = {
    a.to[B].set(
      b = Some(1),
      c = "hi"
    )
  }
}
```

Here is the error message I'm getting when compiling: 
[error]     You have not provided enough arguments to convert from B.
[error]     shapeless.::[shapeless.labelled.FieldType[shapeless.tag.@@[Symbol,String("b")],Some[Int]],shapeless.::[shapeless.labelled.FieldType[shapeless.tag.@@[Symbol,String("c")],String],shapeless.HNil]]
[error]                              
[error] error after rewriting to henkan.convert.Syntax.henkanSyntaxConvert[A](a).to[com.truex.powerline.schema.uplift.surveys.B].set.applyDynamicNamed("apply")(scala.Tuple2("b", Some(1)), scala.Tuple2("c", "hi"))
[error] possible cause: maybe a wrong Dynamic method signature?
[error]     a.to[B].set(

Is there something I'm doing wrong? Thanks.

**Comment by kailuowang** [comment]
It's probably because Some is not exact same type as Option, try use b=Option(1)

**Comment by pigate** [comment]
Thanks!
