### ISSUE TITLE
Relation to chimney

### ISSUE THREAD

**Issue by Krever** [kailuowang/henkan#53]
Would you find a place in the readme or in this issue to briefly describe the differences between henkan and chimney: https://github.com/scalalandio/chimney

I've been using chimney for quite some time and I'm curious what was the motivation to create henkan.

**Comment by kailuowang** [comment]
Thanks for bringing attention to chimney. I believe Henkan was created 1 year before chimney.

**Comment by Krever** [comment]
Oh, my bad than, I forgot to check that, sorry. I will try to compare the feature-set on my own then ;)

My only justification is that Henkan popped up in some trending development list by GitHub and I implicitly assumed its a new project.
